config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'games/bat'

  get 'games/lose'

  get 'games/move'
  post 'games/move'

  get 'games/resume'

  get 'games/shoot_back'
  get 'games/shoot_left'
  get 'games/shoot_right'

  get 'games/start'

  get 'games/win'

  post 'games/wizard'

  resources :high_scores, only: [:new, :create]
end

app/models/game.rb
class Game < ActiveRecord::Base

  # Room laid out as a dodecahedron

  def rooms_available(room)
    [
     [2, 5, 18], [1, 3, 20], [4, 10, 2], [3, 8, 5], [6, 4, 1],
     [5, 7, 19], [8, 14, 6], [7, 9, 4], [10, 13, 8], [9, 11, 3],
     [12, 20, 9], [11, 16, 13], [14, 12, 9], [13, 15, 7], [16, 19, 14],
     [15, 17, 12], [20, 18, 16], [19, 1, 17], [18, 6, 15], [17, 2, 11]
    ][room - 1]
  end

  def room_has_bat?(room)
    room == self.bat_one || room == self.bat_two
  end

  def room_has_wumpit?(room)
    room == self.wumpit
  end

  def room_has_pit?(room)
    room == self.pit_one || room == self.pit_two
  end
end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
  validates :name, presence: true

  def self.order_best_scores
    HighScore.order(moves: :asc, seconds: :asc).limit(5)
  end

  def self.rank_high_scores
    scores = self.order_best_scores
    5.times do |i|
      unless scores[i] == nil
        scores[i].rank = i + 1
        scores[i].save
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: :start
  before_action :save_game, except: :start
  before_action :set_leaderboard

  def start
    available_rooms = (1..20).to_a.shuffle!
    @game = Game.create(room: 20,
                        arrow: 5,
                        counter: 0,
                        timer: 1,
                        player: available_rooms.pop,
                        pit_one: available_rooms.pop,
                        pit_two: available_rooms.pop,
                        bat_one: available_rooms.pop,
                        bat_two: available_rooms.pop,
                        wumpit: available_rooms.pop)
    @player = @game.player
    @arrow = @game.arrow
    next_rooms
    check_senses
    room_choices
  end

  def resume
    @game.room = session[:room]
    @game.player = session[:player]
    @game.bat_one = session[:bat_one]
    @game.bat_two = session[:bat_two]
    @game.pit_one = session[:pit_one]
    @game.pit_two = session[:pit_two]
    @game.wumpit = session[:wumpit]
    @game.arrow = session[:arrow]
    next_rooms
    check_senses
    room_choices
    render "move"
  end

  def move
    @game.update(player: params[:player])
    @player = @game.player
    @arrow = @game.arrow
    if @game.room_has_bat?(@player)
      redirect_to games_bat_path
    end
    if @game.room_has_pit?(@player)
      flash[:lose] = "You have fallen into a pit! You lose!"
      redirect_to games_lose_path
    end
    if @game.room_has_wumpit?(@player)
      flash[:lose] = "You have been eaten by the wumpit! You lose!"
      redirect_to games_lose_path
    end
    respond_to do |format|
      format.html do
        next_rooms
        check_senses
        room_choices
      end
      format.js {}
    end
  end

  def bat
    @game.counter -= 1
    flash.now[:bat_move] = "Bats have carried you to a new room!"
    @game.update(player: rand(20) + 1)
    @player = @game.player
    @arrow = @game.arrow
    next_rooms
    check_senses
    room_choices
  end

  def shoot_back
    @arrow = @game.arrow
    @game.update(arrow: @arrow -= 1)
    if @arrow == 0
      flash[:lose] = "You have run out of ammo! You lose!"
      redirect_to games_lose_path
    end
    @player = @game.player
    @arrow = @game.arrow
    next_rooms
    check_senses
    room_choices
    if @back_room == @game.wumpit
      @game.timer = (Time.now - @game.created_at).to_i
      @game.save
      redirect_to games_win_path
    else
      flash.now[:wumpit] = "The wumpit has moved rooms!"
      @game.update(wumpit: @wumpit_rooms.sample)
      if @game.room_has_wumpit?(@player)
        flash[:lose] = "You startled the wumpit and he found you! You lose!"
        redirect_to games_lose_path
      end
    end
  end

  def shoot_right
    @arrow = @game.arrow
    @game.update(arrow: @arrow -= 1)
    if @arrow == 0
      flash[:lose] = "You have run out of ammo! You lose!"
      redirect_to games_lose_path
    end
    @player = @game.player
    @arrow = @game.arrow
    next_rooms
    check_senses
    room_choices
    if @right_room == @game.wumpit
      @game.timer = (Time.now - @game.created_at).to_i
      @game.save
      redirect_to games_win_path
    else
      flash.now[:wumpit] = "The wumpit has moved rooms!"
      @game.update(wumpit: @wumpit_rooms.sample)
      if @game.room_has_wumpit?(@player)
        flash[:lose] = "You startled the wumpit and he found you! You lose!"
        redirect_to games_lose_path
      end
    end
  end

  def shoot_left
    @arrow = @game.arrow
    @game.update(arrow: @arrow -= 1)
    if @arrow == 0
      flash[:lose] = "You have run out of ammo! You lose!"
      redirect_to games_lose_path
    end
    @player = @game.player
    @arrow = @game.arrow
    next_rooms
    check_senses
    room_choices
    if @left_room == @game.wumpit
      @game.timer = (Time.now - @game.created_at).to_i
      @game.save
      redirect_to games_win_path
    else
      flash.now[:wumpit] = "The wumpit has moved rooms!"
      @game.update(wumpit: @wumpit_rooms.sample)
      if @game.room_has_wumpit?(@player)
        flash[:lose] = "You startled the wumpit and he found you! You lose!"
        redirect_to games_lose_path
      end
    end
  end

  def wizard
    respond_to do |format|
      format.js
    end
  end

  def lose
  end

  def win
  end

  private

  def game_params
    params.require(:game).permit(:player)
  end

  def set_game
    @game = Game.last
    @game.counter += 1
    hint_message = rand(7)
    case hint_message
    when 0
      flash.now[:hint] = "Click the orange grenades to kill the Wumpit!"
    when 1
      flash.now[:hint] = "Did you know Clinton Dreisbach has a pet Wumpit!"
    when 2
      flash.now[:hint] = "When you run out of grenades you lose!"
    when 
      flash.now[:hint] = "Your time and moves gauge your performance!"
    when 4
      flash.now[:hint] = "Click on any blue 'Rooms' to move your player!"
    when 5
      flash.now[:hint] = "Have questions? Check out the 'Rules'"
    when 6
      flash.now[:hint] = "There are two pits so be careful not to fall in!"
    when 7
      flash.now[:hint] = "Don't get caught by bats, they are in two rooms!"
    end
  end

  def set_leaderboard
    HighScore.rank_high_scores
    @high_scores = HighScore.order_best_scores || []
  end

  def next_rooms
    @rooms = @game.rooms_available(@game.player)
    @wumpit_rooms = @game.rooms_available(@game.wumpit)
  end

  def check_senses
    if @rooms.include?(@game.pit_one) || @rooms.include?(@game.pit_two)
      flash.now[:pit] = "You feel a draft nearby"
    end
    if @rooms.include?(@game.bat_one) || @rooms.include?(@game.bat_two)
      flash.now[:bat] = "You hear wings flapping"
    end
    if @rooms.include?(@game.wumpit)
      flash.now[:wumpit] = "You smell a foul stench"
    end
  end

  def room_choices
    @back_room = @rooms[0]
    @left_room = @rooms[1]
    @right_room = @rooms[2]
  end

  def save_game
    session[:room] = @game.room
    session[:player] = @game.player
    session[:pit_one] = @game.pit_one
    session[:pit_two] = @game.pit_two
    session[:bat_one] = @game.bat_one
    session[:bat_two] = @game.bat_two
    session[:wumpit] = @game.wumpit
    session[:arrow] = @game.arrow
  end
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def new
    @high_score = HighScore.new
  end

  def create
    @game = Game.last
    @high_score = HighScore.create(high_score_params)
    @high_score.update(moves: @game.counter, seconds: @game.timer )
    @high_score.save
    redirect_to games_start_path
  end

  private

  def high_score_params
    params.require(:high_score).permit(:name, :moves, :seconds)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/_cave.html.erb
<div class="left icon-bar vertical three-up">
  <a href="<%= root_path %>" class="item">
    <i class="fa fa-home"></i>
    <label>Home</label>
  </a>
  <a href="#" data-reveal-id="myModal" class="item">
    <i class="fa fa-file-text-o"></i>
    <label>Rules</label>
  </a>
  <a href="#" data-reveal-id="leaderModal" class="item">
    <i class="fa fa-list-ol"></i>
    <label>Leader</label>
  </a>
  <a href="<%= games_start_path %>" class="item">
    <i class="fa fa-power-off"></i>
    <label>Start</label>
  </a>
</div>

<div class="row">
  <div class="columns large-10">
    <div class="row">
      <div class="columns large-3 text-center">
        <h2>Moves</h2>
        <h1><%= @game.counter %></h1>
      </div>
      <div class="columns large-6 message-block">
        <% flash.each do |name, msg| -%>
          <% if msg.is_a?(String) %>
            <div data-alert class="alert-box round <%= name.to_s == 'hint' ? 'info' : 'warning' %>">
              <%= content_tag :div, msg %>
              <a href="#" class="close">&times;</a>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="columns large-3 text-center left">
        <h2>Time</h2>
        <h1 id="timer"><%= "#{(Time.now - @game.created_at).to_i} s" %></h1>
      </div>
    </div>

    <div class="row">
      <div class="columns large-5 text-center">
        <%= button_to "#{@left_room}", { action: "move", params: { player: @left_room } }, class: 'button round' %>
        <%= link_to games_shoot_left_path do %>
          <i class="fa fa-bomb"></i>
        <% end %>
      </div>
      <div class="columns large-2 text-center">
        <i class="fa fa-user"></i></br>
        <p class="label round" id="firstStop"><%= "Room #{@game.player}" %></p>
      </div>
      <div class="columns large-5 text-center">
        <%= button_to "#{@right_room}", { action: "move", params: { player: @right_room } }, class: 'button round' %>
        <%= link_to games_shoot_right_path do %>
          <i class="fa fa-bomb" id="thirdStop"></i>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="columns large-centered large-10 text-center">
        <%= button_to "#{@back_room}", { action: "move", params: { player: @back_room } }, class: 'button round' %>
        <%= link_to games_shoot_back_path do %>
          <i class="fa fa-bomb"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="columns large-2">
    <ul>
      <h3><strong>Ammo</strong></h3>
      <% @game.arrow.times do %>
        <i class="fa fa-bomb"></i></br>
      <% end %>
    </ul>
    <%= link_to "Wizard", games_wizard_path, method: 'post', class: 'button tiny', remote: true %>
  </div>
</div>

<div id="myModal" class="reveal-modal" data-reveal>
  <h6>Getting Started with "Wumpit"</h6>
  <p>After you start the game, a hidden maze is constructed. Every time you start a new game you enter a unique cave. The game starts in an empty cavern and you will see three rooms plus your current location. You can move to any adjacent room by clicking it. You also have the choice of throwing a grenade instead of moving. If you choose to throw a grenade it can either wake the Wumpit or kill it depending on it's proximity.</p>
  <h6>Tracking Down The Wumpit</h6>
  <p>The Wumpit makes its lair in one of the caverns in the maze. You know you're getting near the Wumpit when you get an alert that you smell a foul stench. NEVER enter the Wumpit's lair, or else you lose the game.</p>
  <h6>Once The Wumpit Is Located</h6>
  <p>When you think you know where the Wumpit is, it's time to throw your grenade. Click the orange grenade to throw it into the adjacent room. If the cavern you throw into is the Wumpit's lair, you win! If you are wrong, the Wumpit hears the greande and comes looking for you. You only have five grenades, so if you use them all you lose.</p>
  <h6>Caution! Pit</h6>
  <p>When you enter a cavern and receive a message that there is a draft you are approaching a pit. Pits are vast pools of stagnant water that fill a cavern. If you enter a pit cavern, you fall in and lose the game.</p>
  <h6>Do Not Disturb The Bats</h6>
  <p>Some of the caverns in the maze are inhabited by very large bats. The first time you enter a cavern near the bats you will receive an alert that there are bats in the one of the next rooms. If you enter a cavern with bats, you will disturb them. If disturbed, they will pick you up and carry you off to anywhere in the maze...a tunnel, a pit, the Wumpit's lair, or even the cavern where your flight began. Then they choose a new place to live.</p>
  <a class="close-reveal-modal">&#215;</a>
</div>

<div id="leaderModal" class="reveal-modal" data-reveal>
  <div class="row">
    <div class="columns large-2">
      <h2>Rank</h2>
    </div>
    <div class="columns large-4">
      <h2>Name</h2>
    </div>
    <div class="columns large-3">
      <h2>Moves</h2>
    </div>
    <div class="columns large-3">
      <h2>Time</h2>
    </div>
  </div>
  <div class="row">
    <div class="columns large-12">
      <%= render @high_scores %>
    </div>
  </div>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/games/bat.html.erb
<%= render "cave" %>

app/views/games/lose.html.erb
<div class="columns large-centered large-5 message-block">
  <% flash.delete(:hint) %>
  <% flash.each do |name, msg| -%>
    <% if msg.is_a?(String) %>
      <div data-alert class="alert-box warning round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
        <%= content_tag :div, msg %>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  <% end %>
</div>
<div class="columns large-centered large-6 text-center">
  <h1 class="lose">SORRY!</h1>
  <h1 class="lose">YOU LOSE!</h1>
  <%= link_to "Play Again?", games_start_path, class: 'button expand' %>
</div>

app/views/games/move.html.erb
<%= render "cave" %>

app/views/games/move.js.erb
$('.button').hide().show('slow');

app/views/games/shoot_back.html.erb
<%= render "cave" %>

app/views/games/shoot_left.html.erb
<%= render "cave" %>

app/views/games/shoot_right.html.erb
<%= render "cave" %>

app/views/games/start.html.erb
<%= render "cave" %>

app/views/games/win.html.erb
<div class="columns large-centered large-6 text-center">
  <h1>You have slain the Wumpit!</h1>
  <h1>You Win!</h1>
  <%= link_to "Submit score", new_high_score_path, class: 'button' %>
  <%= link_to "Play Again?", games_start_path, class: 'button' %>
</div>

app/views/games/wizard.js.erb
$("i.fa.fa-bomb").removeClass('fa-bomb').addClass('fa-bolt')

app/views/high_scores/_high_score.html.erb
<%= div_for(high_score, class: 'panel radius') do %>
  <div class="columns large-2">
    <%= high_score.rank %>
  </div>
  <div class="columns large-5">
    <%= high_score.name %>
  </div>
  <div class="columns large-3">
    <%= high_score.moves %>
  </div>
  <div class="columns large-2">
    <%= "#{high_score.seconds}" + " s" %>
  </div>
<% end %>

app/views/high_scores/new.html.erb
<div class="columns large-6 large-centered text-center">
  <%= form_for @high_score do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit 'Send', class: 'button' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Wumpit" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href='http://fonts.googleapis.com/css?family=Bowlby+One+SC' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">

    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="columns large-centered large-8 text-center">
  <h1 id="wumpit">Wumpit</h1>
  <%= link_to "New Game", games_start_path, class: 'button' %>
  <a href="#" data-reveal-id="myModal" class="button">
    Rules
  </a>
  <%= link_to "Resume", games_resume_path, class: 'button' %>
</div>

<div id="myModal" class="reveal-modal" data-reveal>
  <h6>Getting Started with "Wumpit"</h6>
  <p>After you start the game, a hidden maze is constructed. Every time you start a new game you enter a unique cave. The game starts in an empty cavern and you will see three rooms plus your current location. You can move to any adjacent room by clicking it. You also have the choice of throwing a grenade instead of moving. If you choose to throw a grenade it can either wake the Wumpit or kill it depending on it's proximity.</p>
  <h6>Tracking Down The Wumpit</h6>
  <p>The Wumpit makes its lair in one of the caverns in the maze. You know you're getting near the Wumpit when you get an alert that you smell a foul stench. NEVER enter the Wumpit's lair, or else you lose the game.</p>
  <h6>Once The Wumpit Is Located</h6>
  <p>When you think you know where the Wumpit is, it's time to throw your grenade. Click the orange grenade to throw it into the adjacent room. If the cavern you throw into is the Wumpit's lair, you win! If you are wrong, the Wumpit hears the greande and comes looking for you. You only have five grenades, so if you use them all you lose.</p>
  <h6>Caution! Pit</h6>
  <p>When you enter a cavern and receive a message that there is a draft you are approaching a pit. Pits are vast pools of stagnant water that fill a cavern. If you enter a pit cavern, you fall in and lose the game.</p>
  <h6>Do Not Disturb The Bats</h6>
  <p>Some of the caverns in the maze are inhabited by very large bats. The first time you enter a cavern near the bats you will receive an alert that there are bats in the one of the next rooms. If you enter a cavern with bats, you will disturb them. If disturbed, they will pick you up and carry you off to anywhere in the maze...a tunnel, a pit, the Wumpit's lair, or even the cavern where your flight began. Then they choose a new place to live.</p>
  <a class="close-reveal-modal">&#215;</a>
</div>